> 생능 출판사 "으뜸 머신러닝" 교과서 내 주요 코드 바탕 실습

**넘파이 소개**

* 데이터 과학을 위한 많은 라이브러리 중 가장 기본이 되는 라이브러리

* 넘파이의 핵심 객체는 ndarray(다차원 배열)로서,동일한 데이터 타입을 가지는 다차원 배열 구조를 의미함

**자신의 드라이브를 코랩에서 사용할 수 있도록 마운트**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


**넘파이는 머신러닝을 위한 데이터 처리의 핵심 도구**

* 넘파이 array() 함수는 파이썬의 리스트와 같은 다양한 인자를 입력받아서 ndarray로 변환하는 기능을 수행

In [2]:
import numpy as np   # numpy의 별칭으로 np를 지정함
my_array = np.array( [ 1, 2, 3] )

In [3]:
my_array.shape

(3,)

In [5]:
my_array.dtype

dtype('int64')

**ndarray를 편리하게 생성하기 - arange, zeros, ones**

---
주로 테스트용으로 데이터를 만들거나 대규모 데이터를 일괄 초기화하는 경우 사용

*   np.arange(): 일정한 간격으로 값을 가지는 배열 생성(NumPy의 arange는 stop 값을 포함하지 않습니다; 즉 start ≤ 값 < stop)

*   np.zeros(): 모든 값이 0인 배열 생성
*   np.ones(): 모든 값이 1인 배열 생성

In [27]:
sequence_array = np.arange(10)
print(sequence_array)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
zero_array = np.zeros((3, 2))
print(zero_array)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [29]:
#(3, 2) shape을 가지는 모든 원소가 1인 ndarray 생성. ,
one_array = np.ones((3, 2))
print(one_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


ndarray의 차원과 크기를 변경하는 reshape


---


reshape() 메서드는 ndarray를 특정 차원 및 크기로 변환

In [30]:
array1 = np.arange(10)
print('array1:\n', array1)

# (2, 5) shape으로 변환
array2 = array1.reshape(2, 5)
print('array2:\n',array2)

#(5, 2) shape으로 변환.
array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [31]:
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [32]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)

array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


**넘파이 활용의 기본 - 브로드캐스팅, 인덱싱, 슬라이싱**

In [6]:
import numpy as np
sal = np.array([240, 260, 220, 255])

In [7]:
sal = sal + 100   # 스칼라값 100은 [100, 100, 100, 100]으로 변환됨
print(sal)

[340 360 320 355]


In [8]:
scores = np.array([58, 72, 93, 94, 89, 78, 99])
scores[3:]     # 인덱스를 생략하면 마지막 요소까지 슬라이싱

array([94, 89, 78, 99])

In [10]:
scores[4:-1]   # 인덱스로 -1을 사용할 경우, 마지막 인덱스 -1 인덱스 78까지 슬라이싱

array([89, 78])

In [15]:
np_array1 = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])  # 2차원 배열(넘파이 다차원 배열)
np_array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np_array1[0, 2]

np.int64(3)

In [17]:
np_array2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],
                     [9, 10, 11, 12], [13, 14, 15, 16]])
np_array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:
np_array2[0:2, 2:4]

array([[3, 4],
       [7, 8]])

In [33]:
# 1에서 부터 9 까지의 1차원 ndarray 생성
# arange(10)은 start가 0으로 자동 설정됨
# 이에 반해 array1 = np.arange(start=1, stop=10)
# 여기서는 시작값을 1로 지정함
# NumPy의 arange는 stop 값을 포함하지 않습니다.
# 즉 start ≤ 값 < stop
array1 = np.arange(start=1, stop=10)
print('array1:',array1)
# index는 0 부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:',value)

array1: [1 2 3 4 5 6 7 8 9]
value: 3


In [34]:
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2])

맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


In [35]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0] )
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


**논리 인덱싱으로 빠르게 데이터 추려내기**

In [20]:
ages = np.array([18, 19, 25, 30, 28])
y = ages > 20
y

array([False, False,  True,  True,  True])

In [21]:
ages[ ages > 20 ]

array([25, 30, 28])

In [23]:
np_array3 = np.array([[1,2,3], [4,5,6], [7,8,9]])
np_array3 > 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [24]:
np_array3 % 2 == 0  # 원소가 2로 나누어 0인가 검사하여 참/거짓 반환

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [26]:
np_array3[ np_array3 % 2 == 0 ]

array([2, 4, 6, 8])

np.sort()sk ndarray.sort() 모두 기본적으로 오른차순으로 행렬 내 원소 정렬

다만, 내림차순으로 정렬하기 위해서는 [::-1]를 적용(예, np.sort()[::-1])

In [36]:
array2d = np.array([[8, 12],
                   [7, 1 ]])

array2d

array([[ 8, 12],
       [ 7,  1]])

In [37]:
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


선형대수 연산 – 행렬 내적과 전치 행렬 구하기

* 행렬 내적: np.dot(A,B)
* 두 행렬이 𝐴(𝑚×𝑛), 𝐵(𝑛×𝑝) 라면
* 𝐴⋅𝐵 = 𝐶(𝑚×𝑝) 즉 결과 행렬 크기는 𝑚×𝑝

In [38]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [39]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
